### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by a-washida** [a-washida/furima_28447#15]
正しくないクレジットカード情報を入力した場合、決済はできないようになっているのですが、エラーハンドリングができていないため処理がそのまま停止します。
少し調べてみた所、今の知識では実装に非常に苦労しそうなので、もし達成要件に入っていないならばこのままチェックお願いします！

- 自身のフリマアプリのURL: https://furima-28447.herokuapp.com/
- Basic認証のID: admin, パスワード: 2222
- 出品者用のメールアドレス: meron@meron, パスワード:112311aq
- 購入者用のメールアドレス: maron@maron, パスワード: 112311aq
- 購入用カードの番号: 4242424242424242
- 購入用カードの期限: 登録時より未来(3月/23年は正常に入力できます)
- 購入用カードのセキュリティコード: 123

**Comment by sho0127** [comment]
鷲田さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
エラーハンドリングに関してはメンターに聞いておきましょう。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
